version: '3.4'

services:
  app:
    image: maia:final
    build:
      context: .
    # ports:
    #   - 8000:8000
    volumes:
      - users:/app/users
    restart: always
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 4444:4444
    depends_on:
      - app
    volumes:
      - users:/app/users
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  users:
    driver: local
